name: Docker

on:
  workflow_call:

jobs:
  docker:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: ["ubuntu-latest", "ubuntu-22.04"]
    steps:
      - uses: actions/checkout@v3

      - name: Setup Docker build
        uses: docker/setup-buildx-action@v3.11.1

      - name: Download a Build Artifact
        uses: actions/download-artifact@v5.0.0
        with:
          # Name of the artifact to download. If unspecified, all artifacts for the run are downloaded.
          name: programa_${{ matrix.os }} # optional

      - name: Docker Login
        # You may pin to the exact commit or the version.
        # uses: docker/login-action@5e57cd118135c172c3672efd75eb46360885c0ef
        uses: docker/login-action@v3.6.0
        with:
          # Server address of Docker registry. If not set then will default to Docker Hub
          #registry: # optional
          # Username used to log against the Docker registry
          username: pedro0000
          # Password or personal access token used to log against the Docker registry
          password: ${{secrets.PASSWORD_DOCKER_HUB}} # optional
          # Specifies whether the given registry is ECR (auto, true or false)
          ecr: auto # optional
          # Log out from the Docker registry at the end of a job
          logout: TRUE # optional, default is true
          # Raw authentication to registries, defined as YAML objects
          registry-auth: # optional
      - name: Build and push Docker images
        # You may pin to the exact commit or the version.
        # uses: docker/build-push-action@263435318d21b8e681c14492fe198d362a7d2c83
        uses: docker/build-push-action@v6.18.0
        with:
          # Build's context is the set of files located in the specified PATH or URL
          context: . # optional
          # Path to the Dockerfile
          file: ./Dockerfile # optional
          # Push is a shorthand for --output=type=registry
          push: true # optional, default is false
          tags: pedro0000/go_ci:${{github.ref_name}} # optional
