name: Continous Delivery

on:
  workflow_call:

jobs:
  EC2:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: ["ubuntu-latest"]
    steps:
      - uses: actions/checkout@v3
      
      - name: Download a Build Artifact
        uses: actions/download-artifact@v5.0.0
        with:
          # Name of the artifact to download. If unspecified, all artifacts for the run are downloaded.
          name: programa_${{ matrix.os }} # optional

      - name: Deploy to Staging server
        uses: easingthemes/ssh-deploy@main
        with:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
          REMOTE_USER: ${{ secrets.REMOTE_USER }}
          TARGET: /home/${{ secrets.REMOTE_USER }}
          EXCLUDE: "/dist/, /node_modules/, /postgres-data/"
          
      - name: Execute remote SSH commands using password
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            export HOST=${{ secrets.DB_HOST }}
            export USER=${{ secrets.DB_USER }}
            export PASSWORD=${{ secrets.DB_PASSWORD }}
            export DBNAME=${{ secrets.DB_DBNAME }}
            export DB_PORT=${{ secrets.DB_PORT }}
            export PORT=8000
            chmod +x main 
            nohup ./main & 
