name: Continous Delivery

on:
  workflow_call:

jobs:
  ECS:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: ["ubuntu-latest"]
    steps:
    - name: Getting task definition
      run: aws ecs describe-task-definition --task-definition Task_API-GO --query taskDefinition > task-definition.json
